export enum ActionType {
    FETCH_EMPLOYEES = 'FETCH_EMPLOYEES',
    ADD_EMPLOYEE = 'ADD_EMPLOYEE',
    FETCH_EMPLOYEES_BY_ID = 'FETCH_EMPLOYEES_BY_ID',
    CHANGE_EMPLOYEE_INFO = 'CHANGE_EMPLOYEE_INFO'
}